# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: VSCode Extension

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 25
      - run: npm ci
        working-directory: ./client
      - run: npm run package
        working-directory: ./client
      - run: npm ci
        working-directory: ./extension
      - run: npm run package
        working-directory: ./extension
      - run: npm test
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: liaradb-explorer
          path: ./extension/liaradb-explorer.vsix
          retention-days: 5
